
services:
  mysql:
    image: mysql:latest
    container_name: mysql_docker
    environment:
      MYSQL_ROOT_PASSWORD: 4Sept2001System.in 
      MYSQL_DATABASE: cloudinary
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

  prodia-service: 
    build:
      context: ./prodia-service
    container_name: prodia-service
    ports:
      - "8082:8082"
    networks:
      - spring-network
    depends_on:
      - mysql

networks:
  spring-network:
    driver: bridge

volumes:
  mysql-volume:
