server:
  port: 8082

spring:
  application:
    name: prodia-service
  datasource:
    url: jdbc:mysql://mysql_docker:3306/cloudinary
    username: root
    password: 4Sept2001System.in
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

prodia:
  token: eb0276c7-47c3-4b5e-b242-5cf330b86ec7